project:
  type: website

website:
  description: "A blog where I infrequently post performance analyses of gitoxide"
  site-url: https://cruessler.github.io
  title: "Performance analyses of gitoxide"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/cruessler
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
